### ISSUE TITLE
Attribute all possible checks in F3548 DSS tests

### ISSUE THREAD

**Issue by BenjaminPelletier** [interuss/monitoring#601]
**report.json is not attached because**
See auto-generated [F3548 sequence view](https://interuss.github.io/monitoring/artifacts/uss_qualifier/reports/f3548/sequence/).

**Test check**
* ASTM SCD DSS: Subscription and entity interaction test scenario
    * [x] Create subscription query succeeds check: #614
* ASTM SCD DSS: Interfaces authentication test scenario
    * [x] Pretty much all checks in Subscription endpoints authentication test step #641
    * [x] Unauthorized requests return the proper error message body #642 
    * [x] Scatter other checks #642 

**Difference from expected behavior**
Occasionally, there are checks that cannot be attributed to a specific participant.  But this is not the case nearly all of the time and nearly all checks should be attributable to one or more participants (usually one).  I think all of the checks mentioned above should be attributable, and therefore should be attributed.

**Comment by Shastick** [comment]
All subtasks are done and #642 was merged. Closing.
